services:
  postgres:
    image: postgres:15
    container_name: neudev_postgres
    environment:
      POSTGRES_DB: neudev_db
      POSTGRES_USER: neudev_admin
      POSTGRES_PASSWORD: Patrik20823
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: neudev_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@neudev.com
      PGADMIN_DEFAULT_PASSWORD: Patrik20823
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: neudev_backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://neudev_admin:${POSTGRES_PASSWORD}@postgres:5432/neudev_db
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: neudev_frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - ./frontend/.env

volumes:
  postgres_data: 